# Generated by Django 6.0.3 on 2026-04-19 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('18:00', '6:00 PM'), ('18:30', '6:30 PM'), ('19:00', '7:00 PM'), ('19:30', '7:30 PM'), ('20:00', '8:00 PM'), ('20:30', '8:30 PM'), ('21:00', '9:00 PM')], max_length=10)),
                ('party_size', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(help_text="The restaurant's story — shown on About page")),
                ('history', models.TextField(help_text='History & founding — shown on About page')),
                ('chef_name', models.CharField(blank=True, max_length=200)),
                ('chef_bio', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('dinner_start', models.TimeField(default=datetime.time(18, 0))),
                ('dinner_end', models.TimeField(default=datetime.time(21, 0))),
                ('hero_image', models.ImageField(blank=True, upload_to='restaurant/')),
                ('chef_image', models.ImageField(blank=True, upload_to='restaurant/')),
            ],
            options={
                'verbose_name': 'Restaurant info',
                'verbose_name_plural': 'Restaurant info',
            },
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='created_at',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=models.CharField(blank=True, help_text='e.g. nuts, dairy, gluten', max_length=300),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='course',
            field=models.CharField(choices=[('main', 'Main Dish'), ('side', 'Side Dish'), ('dessert', 'Dessert')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='main', upload_to='menu/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('note', models.CharField(blank=True, help_text="Optional note e.g. 'Chef's special tasting menu'", max_length=300)),
                ('items', models.ManyToManyField(related_name='daily_menus', to='restaurant.menuitem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
