# Generated by Django 6.0.3 on 2026-04-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation_restaurantinfo_remove_menuitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('ambience', 'Ambience'), ('food', 'Food'), ('chef', 'Chef'), ('events', 'Events')], default='ambience', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number shows first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
